name: Sync to Gitee

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  # Sync to gitee everyday
  schedule:
    - cron: '0 1 * * *'

  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'youzan/vant'
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@v1.2.0
        env:
          # 在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # GitHub 源仓库地址
          source-repo: git@github.com:vant-ui/vant.git
          # Gitee 目标仓库地址
          destination-repo: git@gitee.com:vant-contrib/vant.git
